# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab67e7214e072ddc179f3b40febb42ca9a0c1ffff66af17be261a88127c9f9bf1089192498633daa9f94edb7b377e0c139ca7658fb5f8b45611e2184b00f504

test:
  secret_key_base: 1a077e1cb91e19fa3e6189d810ca312ac84cfa146255959238e727a9e0bb442328019cc0f207a86cb425cba34d38f574f14c818ec39410df0807efa1f4d29589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
